//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIKA5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_
    {
        public int Check_ID { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> ID_InfoCheck { get; set; }
    
        public virtual CheckInfo CheckInfo { get; set; }
        public virtual Product Product { get; set; }
    }
}
