//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIKA5
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckInfo()
        {
            this.Check_ = new HashSet<Check_>();
        }
    
        public int CheckInfo_ID { get; set; }
        public string Address_ { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.TimeSpan> Time_ { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check_> Check_ { get; set; }
        public virtual Users Users { get; set; }
    }
}
