//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIKA5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRACTIKAEntities : DbContext
    {
        public PRACTIKAEntities()
            : base("name=PRACTIKAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Check_> Check_ { get; set; }
        public virtual DbSet<CheckInfo> CheckInfo { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<DescriptionTour> DescriptionTour { get; set; }
        public virtual DbSet<FlightInfo> FlightInfo { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role_> Role_ { get; set; }
        public virtual DbSet<TicketType> TicketType { get; set; }
        public virtual DbSet<Tourist> Tourist { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
