//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIKA5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.CheckInfo = new HashSet<CheckInfo>();
        }
    
        public int ID_User { get; set; }
        public string Name_ { get; set; }
        public string Surname { get; set; }
        public string Middlename { get; set; }
        public Nullable<int> ID_Role { get; set; }
        public string Login_ { get; set; }
        public string Password_ { get; set; }
        public Nullable<int> ID_Tourist { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckInfo> CheckInfo { get; set; }
        public virtual Role_ Role_ { get; set; }
        public virtual Tourist Tourist { get; set; }
    }
}
